name: wstar_retailer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  adobe_xd:
  pinput:
  font_awesome_flutter:
  persistent_bottom_nav_bar:
  intl:
  cupertino_icons: ^1.0.0
  fl_chart: ^0.12.3
  charts_flutter: ^0.10.0
  date_utils: ^0.1.0+3
  syncfusion_flutter_datepicker: ^18.4.49-beta
  flutter_date_pickers: ^0.1.10
  flutter_barcode_scanner: ^1.0.2
  intro_slider: ^2.3.4
  image_picker: ^0.6.7+2
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.30
  google_map_location_picker: ^3.3.4
  flutter_localizations:
    sdk: flutter
  flutter_lock_screen: '^1.0.6'
  splashscreen: ^1.3.5
  shared_preferences: ^0.5.7+3
  awesome_dialog: ^1.1.3
  dropdown_formfield: ^0.1.2
  qr_code_scanner: ^0.3.5
  firebase_messaging: ^5.0.3
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^5.0.0
  outline_material_icons: ^0.1.0
  provider:
  flutter_launcher_icons: ^0.7.2
  url_launcher: ^5.0.3
  cloud_firestore: ^0.14.0
  flutter_spinkit: ^4.1.2+1
  # stream chat
  stream_chat_flutter: ^0.2.20+3
  rxdart: ^0.24.0
  bloc: ^4.0.0
  get_it: ^4.0.0
  uuid: ^2.0.4
  flutter_local_notifications: ^1.4.4+4
  audioplayers: ^0.17.4
  timeago: ^2.0.29
  agora_rtc_engine: ^3.1.3
  permission_handler: ^5.0.1
  video_player: ^1.0.0
  chewie: ^0.12.2
  readmore: ^1.0.0
  #bubble: ^1.1.9+1
  flutter_chat_bubble: ^1.0.2
  connectivity: ^2.0.2
  multi_image_picker: ^4.6.1
  carousel_pro: ^1.0.0
  file_picker: ^2.0.12
  comment_tree: ^0.1.2
  progress_dialog: ^1.2.4
  overlay_support: ^1.0.5
  flutter_callkeep: ^0.1.8
  sqflite: ^1.3.1
  path_provider: ^1.6.18
  cached_network_image: ^2.3.1
  #google_maps_place_picker: ^0.9.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/images/
    - assets/swiftly.mp3
    - assets/sent.mp3
    - assets/facebook_pop.mp3